### ISSUE TITLE
Refactor formula to match template-formula

### ISSUE THREAD

**Issue by alxwr** [saltstack-formulas/dnsmasq-formula#22]
- use `defaults.yaml` & Co.
- reduce Pillar data
i.e. this needs to go:

```
dnsmasq:
  dnsmasq_conf: salt://dnsmasq/files/dnsmasq.conf
  dnsmasq_hosts: salt://dnsmasq/files/dnsmasq.hosts
  dnsmasq_cnames: salt://dnsmasq/files/dnsmasq.cnames
  dnsmasq_conf_dir: salt://dnsmasq/files/dnsmasq.d
```
